### ISSUE TITLE
请教一下 为什么类别项只能翻译第一个？

### ISSUE THREAD

**Issue by tianyeobk** [LightAPIs/auto-translation-nfo#2]
请教一下 为什么类别项只能翻译第一个？

**Comment by dragonish** [comment]
因为并没有处理多个同名元素的情况。本身只内置了一个批量替换类别的功能，可以在工作目录中创建一个 `tag.json` 文件写入类似以下内容后再运行程序：

```json
{
  "replace": [
    {
      "original": "旧类别1"
      "result": "新类别1"
    },
    {
      "original": "旧类别2"
      "result": "新类别2"
    }
  ]
}
```

**Comment by tianyeobk** [comment]
开始运行
************************************************
工作目录: F:\1\temp
处理元素节点: ['title', 'plot', 'tag', 'genre']
日志级别: all
自动备份: True
替换标签: False
************************************************
Traceback (most recent call last):
  File "main.py", line 390, in <module>
  File "main.py", line 144, in detect_walk
  File "tag.py", line 10, in __init__
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 7 (char 54)
[16400] Failed to execute script main




这是啥意思啊 大哥

**Comment by dragonish** [comment]
哦，我写的示例里遗漏了逗号：

```json
{
  "replace": [
    {
      "original": "旧类别1",
      "result": "新类别1"
    },
    {
      "original": "旧类别2",
      "result": "新类别2"
    }
  ]
}
```

**Comment by tianyeobk** [comment]
还是报错......Traceback (most recent call last):
  File "main.py", line 390, in <module>
  File "main.py", line 186, in detect_walk
KeyError: 'delete'
[26076] Failed to execute script main


而且还是2024-12-15 17:31:34,535 INFO: 原 tag: AVC1
2024-12-15 17:31:35,702 INFO: 新 tag: AVC1

**Comment by dragonish** [comment]
```json
{
  "replace": [
    {
      "original": "旧类别1",
      "result": "新类别1"
    },
    {
      "original": "旧类别2",
      "result": "新类别2"
    }
  ],
  "delete": []
}
```

`delete` 键是必需的。

**Comment by tianyeobk** [comment]
不好用还是报错 哥们儿要不你从新做一下 我赞助点☺
